version: "1"
services:
  hive_metastore:
    image: mysql/mysql-server:8.0.28
    hostname: hive_metastore
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ../../data/hive/metastore:/var/lib/mysql
      - ./scripts:/scripts:ro
      - ./scripts/setup_metastore.sql:/docker-entrypoint-initdb.d/1.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "hadoop"
      MYSQL_PASSWORD: "hadoop"
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  datanode:
    image: apache/hadoop:3
    env_file:
      - ./config/hadoop-config.yaml
    volumes:
      - ../../data/hadoop/data:/tmp/hadoop-hadoop/dfs/data:rw
      - ./scripts:/scripts:ro
    ports:
      - 9864:9864
    command: /scripts/initialize_datanode.sh
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  namenode:
    image: azoz01/hadoop-namenode
    # hostname: namenode
    hostname: localhost
    ports:
      - 9870:9870
      - 50070:50070
    env_file:
      - ./config/hadoop-config.yaml
    volumes:
      - ../../data/hadoop/name:/tmp/hadoop-hadoop/dfs/name:rw
      - ./scripts:/scripts:ro
    command: /scripts/initialize_namenode.sh
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    container_name: namenode
  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./config/hadoop-config.yaml
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  nodemanager:
    image: apache/hadoop:3
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./config/hadoop-config.yaml
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  redis:
    image: redis
    ports:
      - 6379:6379
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    volumes:
      - ../../data/elastic:/usr/share/elasticsearch/data:rw
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  nifi:
    image: azoz01/nifi
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "514:514/tcp"
      - "514:514/udp"
      - "2055:2055/udp"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=user
      - SINGLE_USER_CREDENTIALS_PASSWORD=useruseruser
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    # volumes: 
    #   - ../../data/nifi/database_repository:/opt/nifi/nifi-current/database_repository
    #   - ../../data/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
    #   - ../../data/nifi/content_repository:/opt/nifi/nifi-current/content_repository
    #   - ../../data/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
    #   - ../../data/nifi/state:/opt/nifi/nifi-current/state
    #   - ../../data/nifi/logs:/opt/nifi/nifi-current/logs
